server {
    listen 80;
    server_name api.bulletin.local;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.bulletin.local;

    ssl_certificate /etc/nginx/certs/bulletin.local.pem;
    ssl_certificate_key /etc/nginx/certs/bulletin.local-key.pem;

    root /workspace/apps/api/public;
    index index.php;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass api:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        internal;
    }
}
