server {
    listen 80;
    server_name app.bulletin.local;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name app.bulletin.local;

    ssl_certificate /etc/nginx/certs/bulletin.local.pem;
    ssl_certificate_key /etc/nginx/certs/bulletin.local-key.pem;

    root /workspace/apps/web/dist;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}
