server {
    listen 80;
    server_name api.dev.social.aleherse.com app.dev.social.aleherse.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.dev.social.aleherse.com;

    ssl_certificate /etc/socialbulletin/certs/socialbulletin.pem;
    ssl_certificate_key /etc/socialbulletin/certs/socialbulletin-key.pem;

    resolver 127.0.0.11 valid=10s ipv6=off;
    set $api_upstream http://api:8000;

    location / {
        proxy_pass $api_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 443 ssl;
    server_name app.dev.social.aleherse.com;

    ssl_certificate /etc/socialbulletin/certs/socialbulletin.pem;
    ssl_certificate_key /etc/socialbulletin/certs/socialbulletin-key.pem;

    resolver 127.0.0.11 valid=10s ipv6=off;
    set $web_upstream https://web:3000;

    location / {
        proxy_pass $web_upstream;
        proxy_ssl_verify off;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
