nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(WEB_ALLOWED_ORIGIN)%']
        allow_methods: []
        allow_headers: []
        expose_headers: []
        max_age: 0
