security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    cookie_users:
      id: SocialBulletin\Api\Security\UserProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern: ^/
      stateless: true
      provider: cookie_users
      jwt: ~

  access_control:
    - { path: ^/api/auth/register-or-login$, roles: PUBLIC_ACCESS }
    - { path: ^/api/auth/logout$, roles: PUBLIC_ACCESS }
    - { path: ^/api/me$, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api/doc.json$, roles: PUBLIC_ACCESS }
